// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAQ9ypLFO1dn6106UrKLcMVZ26hKoe2k',
    appId: '1:188056389587:web:8a03c17747383320bf1126',
    messagingSenderId: '188056389587',
    projectId: 'e-commerce-app-8dc3b',
    authDomain: 'e-commerce-app-8dc3b.firebaseapp.com',
    storageBucket: 'e-commerce-app-8dc3b.appspot.com',
    measurementId: 'G-X6DMBRKJ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKS1WOzzShjLqgkvG6utAwGkDZQGLbG2M',
    appId: '1:188056389587:android:2ab17149ae9dbca6bf1126',
    messagingSenderId: '188056389587',
    projectId: 'e-commerce-app-8dc3b',
    storageBucket: 'e-commerce-app-8dc3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLA8nNZchHEbSuSCOjtCJpr1uoCEo-fbw',
    appId: '1:188056389587:ios:a43ce2f6cd73b8cfbf1126',
    messagingSenderId: '188056389587',
    projectId: 'e-commerce-app-8dc3b',
    storageBucket: 'e-commerce-app-8dc3b.appspot.com',
    iosBundleId: 'com.muhammadfiaz.buzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLA8nNZchHEbSuSCOjtCJpr1uoCEo-fbw',
    appId: '1:188056389587:ios:7754a09a2996c2b0bf1126',
    messagingSenderId: '188056389587',
    projectId: 'e-commerce-app-8dc3b',
    storageBucket: 'e-commerce-app-8dc3b.appspot.com',
    iosBundleId: 'com.muhammadfiaz.buzz.RunnerTests',
  );
}
